#configuración base de datos
default: &default
  adapter: postgresql
  encoding: unicode
  database: ecobazarchristiandroguett
  username: postgres
  password: Alta_1907
  host: localhost

development:
  <<: *default
  database: ecobazarchristiandroguett_development

test:
  <<: *default
  database: ecobazarchristiandroguett_test


production:
  <<: *default
  database: ecobazarchristiandroguett
  username: nemus
  password: Alta_1907
